from __future__ import annotations

from enum import StrEnum


class MarketType(StrEnum):
    SPOT = "spot"
    MARGIN = "margin"
    FUTURES = "futures"


class OperatingMode(StrEnum):
    DISABLED = "disabled"
    SHADOW = "shadow"
    PAPER = "paper"
    LIVE = "live"


class Action(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"


class SignalStatus(StrEnum):
    VALID = "valid"
    EXPIRED = "expired"
    SKIPPED = "skipped"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP_MARKET = "STOP_MARKET"


class OrderStatus(StrEnum):
    NEW = "NEW"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    MISSED = "MISSED"


class PositionStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class ConsensusLabel(StrEnum):
    LONG_3_3 = "3/3 LONG"
    SHORT_3_3 = "3/3 SHORT"
    LONG_2_3 = "2/3 LONG"
    SHORT_2_3 = "2/3 SHORT"
    LONG_2_2 = "2/2 LONG"
    SHORT_2_2 = "2/2 SHORT"
    CONFLICT = "CONFLICT"
    NO_CONSENSUS = "NO_CONSENSUS"


class SlippageModelName(StrEnum):
    FIXED_BPS = "fixed_bps"
    SPREAD_BASED = "spread_based"
    ORDERBOOK_BASED = "orderbook_based"


class TargetMode(StrEnum):
    FIXED = "fixed"
    STRUCTURE = "structure"
    RR = "rr"


# Reason codes are stable audit strings. Do not rename without a version bump.
STALE_MARKET_DATA = "STALE_MARKET_DATA"
INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
BAD_SPREAD = "BAD_SPREAD"
LOW_LIQUIDITY = "LOW_LIQUIDITY"
HIGH_VOLATILITY = "HIGH_VOLATILITY"
BELOW_THRESHOLD = "BELOW_THRESHOLD"
TREND_UP = "TREND_UP"
TREND_DOWN = "TREND_DOWN"
ABOVE_VWAP = "ABOVE_VWAP"
BELOW_VWAP = "BELOW_VWAP"
POSITIVE_CVD = "POSITIVE_CVD"
NEGATIVE_CVD = "NEGATIVE_CVD"
STRONG_BID_IMBALANCE = "STRONG_BID_IMBALANCE"
STRONG_ASK_IMBALANCE = "STRONG_ASK_IMBALANCE"
HIGH_VOLUME = "HIGH_VOLUME"
BREAKOUT = "BREAKOUT"
BREAKDOWN = "BREAKDOWN"
STRATEGY_ERROR = "STRATEGY_ERROR"
QUEUE_SATURATED = "QUEUE_SATURATED"
EXPIRED_SIGNAL = "EXPIRED_SIGNAL"
ENGINE_DISABLED = "ENGINE_DISABLED"
LIVE_LOCKED = "LIVE_LOCKED"
SPOT_SHORT_NOT_SUPPORTED = "SPOT_SHORT_NOT_SUPPORTED"
EXISTING_POSITION = "EXISTING_POSITION"
ORDER_BELOW_MIN_NOTIONAL = "ORDER_BELOW_MIN_NOTIONAL"
VOTES_NOT_ARRIVED = "VOTES_NOT_ARRIVED"
ENTRY_THROTTLED = "ENTRY_THROTTLED"
STOP_COOLDOWN = "STOP_COOLDOWN"
NO_STRUCTURE_TARGET = "NO_STRUCTURE_TARGET"
TARGET_BEYOND_HOUR = "TARGET_BEYOND_HOUR"
STOP_TOO_WIDE = "STOP_TOO_WIDE"
STOP_TOO_TIGHT = "STOP_TOO_TIGHT"
STOP_WIDENED_TO_MIN = "STOP_WIDENED_TO_MIN"
TARGET_EXTENDED_FOR_FEES = "TARGET_EXTENDED_FOR_FEES"
MARGIN_PAPER_ONLY = "MARGIN_PAPER_ONLY"
STOP_ATR_FALLBACK = "STOP_ATR_FALLBACK"
NET_RR_TOO_LOW = "NET_RR_TOO_LOW"
INSUFFICIENT_LIQUIDITY = "INSUFFICIENT_LIQUIDITY"
MAX_RISK_PER_TRADE = "MAX_RISK_PER_TRADE"
MAX_DAILY_LOSS = "MAX_DAILY_LOSS"
MAX_DAILY_DRAWDOWN = "MAX_DAILY_DRAWDOWN"
MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
MAX_SYMBOL_EXPOSURE = "MAX_SYMBOL_EXPOSURE"
MAX_TOTAL_EXPOSURE = "MAX_TOTAL_EXPOSURE"
INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
PERSISTENCE_UNAVAILABLE = "PERSISTENCE_UNAVAILABLE"
JEV_UNAVAILABLE = "JEV_UNAVAILABLE"
JEV_FALLBACK = "JEV_FALLBACK"
JEV_LOW_CONTINUATION = "JEV_LOW_CONTINUATION"
JEV_HIGH_REVERSAL = "JEV_HIGH_REVERSAL"
JEV_FALSE_BREAKOUT = "JEV_FALSE_BREAKOUT"
JEV_PRESSURE_DISAGREES = "JEV_PRESSURE_DISAGREES"
JEV_LIQUIDITY_SWEEP = "JEV_LIQUIDITY_SWEEP"
OPENAI_NOT_CONFIGURED = "OPENAI_NOT_CONFIGURED"
OPENAI_CALLS_DISABLED = "OPENAI_CALLS_DISABLED"
OPENAI_TIMEOUT = "OPENAI_TIMEOUT"
OPENAI_INVALID_SCHEMA = "OPENAI_INVALID_SCHEMA"
OPENAI_ERROR = "OPENAI_ERROR"
OPENAI_CIRCUIT_OPEN = "OPENAI_CIRCUIT_OPEN"
OPENAI_REGIME_BLOCK = "OPENAI_REGIME_BLOCK"
OPENAI_LOW_CONFIDENCE = "OPENAI_LOW_CONFIDENCE"
OPENAI_ANOMALY = "OPENAI_ANOMALY"
BASELINE_NO_TRADE = "BASELINE_NO_TRADE"
RISK_REJECTED = "RISK_REJECTED"
EXCHANGE_RULES_UNAVAILABLE = "EXCHANGE_RULES_UNAVAILABLE"
NO_CREDENTIALS = "NO_CREDENTIALS"
SLIPPAGE_BOOK_FALLBACK = "SLIPPAGE_BOOK_FALLBACK"
